config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :restaurants, only: [:show] do
    resources :reviews, only: [:new, :create, :show, :index]
  end
  resources :reviews, only: [:show]
  resources :users, only: [:show]
  resources :visits
  resources :cuisines, only: [:show]
  resources :cities, only: [:show]
  resources :countries, only: [:show]
  get 'countriesAZ', to: 'countries#sortAZ'
  get 'countriesMost', to: 'countries#sortMost'
  get 'citiesAZ', to: 'cities#sortAZ'
  get 'citiesMost', to: 'cities#sortMost'
  get 'cuisinesAZ', to: 'cuisines#sortAZ'
  get 'cuisinesMost', to: 'cuisines#sortMost'
  get 'restaurantsAZ', to: 'restaurants#index'
  get 'restaurantsRating', to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :restaurants
  belongs_to :country


  validates :name, uniqueness: true

end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  has_many :restaurants, through: :cities
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurants

  validates :name, format: {with: /\A[A-Z]{1}[a-z]+(\z|\s[A-Z]{1}[a-z]+)/, message: "of cuisine must be correctly capitalized and only contain alphabetical characters (e.g. Fast Food)"}

  validates :name, uniqueness: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  belongs_to :cuisine
  belongs_to :city
  has_many :visits
  has_many :users, through: :visits

  def average_rating
    if self.reviews.any?
      sum = 0
      self.reviews.each do |review|
        sum += review.rating
      end
      sum/(self.reviews.count.round(2))
    else
      0
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :rating, presence: true
  validates :content, length: {in: 15..500, message: "Review must be in betweeen 15 and 500 characters."}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :visits
  has_many :restaurants, through: :visits

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates_uniqueness_of :user_id, :scope => :restaurant_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def sortAZ
    @cities = City.all.sort_by{|city| city.name}
    render json: @cities
  end

  def sortMost
    @cities = City.all.sort_by{|city| city.restaurants.count}.reverse
    render json: @cities
  end

  def show
    @city = City.find_by(id: params[:id])
    render json: @city
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def sortAZ
    @countries = Country.all.sort_by{|country| country.name}
    render json: @countries
  end

  def sortMost
    @countries = Country.all.sort_by{|country| country.restaurants.count}.reverse
    render json: @countries
  end

  def show
    @country = Country.find(params[:id])
    render json: @country
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def sortAZ
    @cuisines = Cuisine.all.sort_by{|cuisine| cuisine.name}
    render json: @cuisines
  end

  def sortMost
    @cuisines = Cuisine.all.sort_by{|cuisine| cuisine.restaurants.count}.reverse
    render json: @cuisines
  end

  def show
    @cuisine = Cuisine.find(params[:id])
    render json: @cuisine
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all.sort_by{|restaurant| restaurant.name}
    render json: @restaurants
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    respond_to do |f|
      f.html {render 'restaurants/show'}
      f.json {render json: @restaurant}
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    render json: @restaurant.reviews
  end

  def show
    @review = Review.find(params[:id])
    render json: @review
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(restaurant_id: params[:restaurant_id])
    render layout: false
  end

  def create
    @restaurant = Restaurant.find(params[:review][:restaurant_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.valid?
      @review.save
      redirect_to restaurant_review_path(@restaurant, @review), layout: false
    else
      render :new
    end
  end
  

  private
  def review_params
    params.require(:review).permit(:restaurant_id, :rating, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @restaurants = Restaurant.all.sort_by{|restuarant| restuarant.name}
    @visit = Visit.new
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def new
    @visit = Visit.new
  end

  def create
    visit = Visit.create(user_id: current_user.id, restaurant_id: params[:restaurant])
    redirect_to user_path(current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def calculate_average(restaurant)
    if restaurant.reviews.none?
      "This restaurant has no reviews."
    else
      sum = 0
      restaurant.reviews.each do |review|
        sum += review.rating
      end
      "Average Rating: #{sum/(restaurant.reviews.count.round(2))} Stars"
    end
  end

  def restaurant_errors(restaurant, error_messages)
    error_messages << restaurant.errors.full_messages if restaurant.errors.any?
    error_messages << restaurant.cuisine.errors.full_messages if restaurant.cuisine.errors.any?
    error_messages << restaurant.city.errors.full_messages if restaurant.city.errors.any?
  end

  def count_restaurants_greeting()
    if current_user.restaurants.any?
      if current_user.restaurants.count == 1
          greeting = "<h3>Congratulations! You visited your first Michelin 3-Star Restaurant!</h3>"
      elsif current_user.restaurants.count > 1
          greeting = "<h3>You've Visited #{current_user.restaurants.count} Michelin 3-Star Restaurants So Far!</h3>"
      end
      raw("#{greeting}<h5>There are #{Restaurant.all.count - current_user.restaurants.count} more Michelin 3-Star Restaurants in the world for you to try!</h5>")
    else
      raw("<h3> You haven't visited any 3-Star Michelin Restaurants Yet</h3>")
    end
  end

  def add_or_see_review(restaurant)
    if current_user.reviews.detect{|review| review.restaurant_id == restaurant.id}
      review = Review.find_by(restaurant_id: restaurant.id)
      link = "<a class='see_review review_#{review.id}' href='/reviews/#{review.id}'>See Your Review</a>"
      raw("#{link}<div class='review_#{review.id}'></div>")
    else
      link = "<a class='add_review restaurant_#{restaurant.id}' href='/restaurants/#{restaurant.id}/reviews/new'>Add Review</a>"
      raw("#{link}<div class='restaurant_#{restaurant.id}'></div>")
    end
  end

end

app/views/layouts/_header.html.erb
<nav class ="">
    <h3>
      <%= link_to 'Home', root_path %> |
      <% if user_signed_in? %>
        <%= link_to 'Your Profile', user_path(current_user) %> |
        <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %> |
        <%= link_to 'Log In', new_user_session_path %>
      <% end %>
    </h3>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>RestaurantReviewRailsApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'welcome' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.cuisine.name %> Cuisine |
  <% if @restaurant.city.name != @restaurant.city.country.name %>
  <%= @restaurant.city.name %>, <%= @restaurant.city.country.name %>
  <% else %>
  <%= @restaurant.city.name %>
  <% end %></h3>
  <h6><%= link_to "Visit Website", @restaurant.website_url, target: :_blank %></h6>
<h4><%= calculate_average(@restaurant) %></h4>

<% if @restaurant.reviews.any? %>
  <%= link_to "See Reviews", restaurant_reviews_path(@restaurant), id: "list_reviews"%>
  <div class="list_reviews">
  </div>
<% end %>




<% if user_signed_in? && current_user.admin == true %>
  <div>
    <%= button_to 'Delete Restaurant Listing', {controller: 'restaurants', action: 'destroy', restaurant_id: @restaurant.id}, method: "delete" %>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2>
        Please fix the following <%= pluralize(review.errors.count, "error") %> with your review:
      </h2>
      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :restaurant_id %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: 1...6 %><br>
  <%= f.text_area :content%><br>
  <%= f.submit 'Submit'%>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Your Review for <%=@review.restaurant.name %></h1>

<%= render partial: 'form', locals: {review: @review} %>

app/views/reviews/new.html.erb
<%= render partial: 'form', locals: {restaurant: @restaurant, review: @review} %>
<div class="reviewResult">
  <h3 class="reviewRating"></h3>
  <h4 class="reviewContent"></h4>
</div>

app/views/users/show.html.erb
<h1>Your Profile</h1>
<h5>Logged in as <%= current_user.email %></h5>

<%= count_restaurants_greeting %>

<ol>
<% current_user.restaurants.each do |restaurant| %>
  <li>
    <%= link_to restaurant.name, restaurant_path(restaurant) %><br>
    <%= add_or_see_review(restaurant) %>
    <br>
  </li>
<% end %>
</ol>

<%= form_for (@visit) do |f| %>
  <%= select_tag :restaurant, options_from_collection_for_select(@restaurants, "id", "name"), {:prompt => "Enter a new restaurant you've visited:"} %>
  <%= f.submit "Submit"%>
<% end %>

app/views/welcome/home.html.erb
<h1>Your Michelin 3-Star Restaurant Guide</h1>
<h2>Personalized for Fine Dining Lovers Like You!</h2>

<div>
  <select id="browse_bar">
    <option>Browse By:</option>
    <option value="countriesAZ" >Country (A-Z)</option>
    <option value="countriesMost">Country (Most)</option>
    <option value="citiesAZ">City (A-Z)</option>
    <option value="citiesMost">City (Most)</option>
    <option value="cuisinesAZ">Cuisine (A-Z)</option>
    <option value="cuisinesMost">Cuisine (Most)</option>
    <option value="restaurantsAZ">View All (A-Z)</option>
    <option value="restaurantsRating">View All (Rating)</option>
  </select>
</div>
<div id="display_list">

</div>
<% if !user_signed_in? %>
  <h5>Log In or Sign Up to track your dining experiences and post a review!</h5>
<% end %>